import { constants, closeSync, existsSync, lstatSync, mkdirSync, openSync, readFileSync, readdirSync, writeSync } from 'fs';
import { join } from 'path';
import { execFileSync } from 'child_process';
import { canonicalize } from '../../core/evidence/canonical-json';
import { buildRefactorCanaryReceipt, promoteRefactorActivation, validateRefactorActivationEvent, validateRefactorCanaryReceipt, type RefactorActivationEventV1, type RefactorActivationLevel, type RefactorCanaryReceiptV1 } from '../../core/refactor/activation';
import { resolveGitCommonDirectory } from '../git/common-directory';

function directory(repoRoot: string): string { return join(resolveGitCommonDirectory(repoRoot), 'repo-harness', 'refactor-activation', 'v1'); }
function readableDirectory(repoRoot: string): string | null { const path = directory(repoRoot); if (!existsSync(path)) return null; const stat = lstatSync(path); if (!stat.isDirectory() || stat.isSymbolicLink()) throw new Error('refactor activation store is unsafe'); return path; }
function readJson(path: string): unknown { const stat = lstatSync(path); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error('refactor activation evidence is unsafe'); return JSON.parse(readFileSync(path, 'utf8')); }
function append(path: string, value: unknown): void { const bytes = Buffer.from(`${canonicalize(value as never)}\n`); if (existsSync(path)) { if (!readFileSync(path).equals(bytes)) throw new Error('refactor activation digest names different bytes'); return; } let fd: number; try { fd = openSync(path, constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY | constants.O_NOFOLLOW, 0o600); } catch (error) { throw new Error('cannot append refactor activation evidence', { cause: error }); } try { let offset = 0; while (offset < bytes.length) offset += writeSync(fd, bytes, offset, bytes.length - offset); } finally { closeSync(fd); } }
function root(repoRoot: string): string { const path = directory(repoRoot); mkdirSync(path, { recursive: true, mode: 0o700 }); if (!lstatSync(path).isDirectory() || lstatSync(path).isSymbolicLink()) throw new Error('refactor activation store is unsafe'); return path; }
export function appendRefactorCanaryReceipt(repoRoot: string, input: Omit<RefactorCanaryReceiptV1, 'protocol' | 'kind' | 'receiptSha256'>): RefactorCanaryReceiptV1 { const receipt = buildRefactorCanaryReceipt(input); append(join(root(repoRoot), `canary-${receipt.receiptSha256.slice(7)}.json`), receipt); return receipt; }
export function readRefactorCanaryReceipts(repoRoot: string): readonly RefactorCanaryReceiptV1[] { const path = readableDirectory(repoRoot); if (!path) return []; return Object.freeze(readdirSync(path).filter((name) => /^canary-[a-f0-9]{64}\.json$/u.test(name)).sort().map((name) => validateRefactorCanaryReceipt(readJson(join(path, name)) as RefactorCanaryReceiptV1))); }
export function readRefactorActivationLevel(repoRoot: string): RefactorActivationLevel { const path = readableDirectory(repoRoot); if (!path) return 'off'; const receipts = readRefactorCanaryReceipts(repoRoot); const remaining = readdirSync(path).filter((entry) => /^event-[a-f0-9]{64}\.json$/u.test(entry)).map((name) => validateRefactorActivationEvent(readJson(join(path, name)) as RefactorActivationEventV1)); let level: RefactorActivationLevel = 'off'; while (remaining.length) { const matches = remaining.filter((entry) => entry.previousLevel === level); if (matches.length !== 1) throw new Error('refactor activation event chain is branching or disconnected'); const event = matches[0]!; const rebuilt = promoteRefactorActivation({ currentLevel: level, nextLevel: event.nextLevel, repositoryId: event.repositoryId, targetRevision: event.targetRevision, receipts, observedAt: event.observedAt }); if (rebuilt.eventSha256 !== event.eventSha256) throw new Error('refactor activation event is not bound to its canary receipts'); remaining.splice(remaining.indexOf(event), 1); level = event.nextLevel; } return level; }
export function advanceRefactorActivation(input: { readonly repo_root: string; readonly repository_id: string; readonly target_revision: string; readonly next_level: RefactorActivationLevel; readonly observed_at: string }): RefactorActivationEventV1 { const head = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: input.repo_root, encoding: 'utf8' }).trim(); if (head !== input.target_revision) throw new Error('activation target revision is not the current repository HEAD'); const currentLevel = readRefactorActivationLevel(input.repo_root); if (currentLevel === input.next_level) { const path = readableDirectory(input.repo_root)!; const matches = readdirSync(path).filter((entry) => /^event-[a-f0-9]{64}\.json$/u.test(entry)).map((name) => validateRefactorActivationEvent(readJson(join(path, name)) as RefactorActivationEventV1)).filter((event) => event.nextLevel === input.next_level && event.repositoryId === input.repository_id && event.targetRevision === input.target_revision && event.observedAt === input.observed_at); if (matches.length === 1) return matches[0]!; }
  const event = promoteRefactorActivation({ currentLevel, nextLevel: input.next_level, repositoryId: input.repository_id, targetRevision: input.target_revision, receipts: readRefactorCanaryReceipts(input.repo_root), observedAt: input.observed_at }); append(join(root(input.repo_root), `event-${event.eventSha256.slice(7)}.json`), event); return event; }
