import { afterEach, describe, expect, test } from 'bun:test';
import { execFileSync } from 'child_process';
import { cpSync, mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { buildWorkDemand, type WorkDemandActorV1 } from '../../src/core/engineers/work-demand';
import { bindEngineer, readEngineerBindingStatus, retireEngineer } from '../../src/effects/engineers/binding-store';
import { loadEngineerProfile } from '../../src/effects/engineers/profile-store';
import { repoHarnessRepoIdFor } from '../../src/effects/repo-registry';
import { readWorkDemandStatus, transitionWorkDemand, WorkDemandStoreError } from '../../src/effects/engineers/work-demand-store';

const source=process.cwd(),roots:string[]=[];const CAP='capability.verification.evals-checks',ENGINEER=`engineer:${CAP}`,BINDING='11111111-1111-4111-8111-111111111111';
afterEach(()=>{while(roots.length)rmSync(roots.pop()!,{recursive:true,force:true});});
function fixture(){const root=mkdtempSync(join(tmpdir(),'work-demand-store-'));roots.push(root);execFileSync('git',['init','-q','--initial-branch=main'],{cwd:root});mkdirSync(join(root,'.archcontext/model'),{recursive:true});mkdirSync(join(root,'agents'),{recursive:true});cpSync(join(source,'.archcontext/model/nodes'),join(root,'.archcontext/model/nodes'),{recursive:true});cpSync(join(source,'agents/engineers'),join(root,'agents/engineers'),{recursive:true});writeFileSync(join(root,'README.md'),'fixture\n');execFileSync('git',['add','.'],{cwd:root});execFileSync('git',['-c','user.name=Test','-c','user.email=test@example.invalid','commit','-qm','base'],{cwd:root});const profile=loadEngineerProfile(root,ENGINEER);bindEngineer(root,{engineer_id:ENGINEER,idempotency_key:'bind',provider:'codex',provider_thread_id:'thread',host_id:'local',engineer_contract_revision:profile.engineer_contract_revision,expected_current_digest:null,expected_binding_generation:0,expected_binding_id:null,expected_engineer_contract_revision:profile.engineer_contract_revision,binding_id:()=>BINDING,now:()=> '2026-09-04T00:00:00.000Z'});return root;}
function actor(root:string):WorkDemandActorV1{const p=loadEngineerProfile(root,ENGINEER);const b=readEngineerBindingStatus(root,ENGINEER,p.engineer_contract_revision).binding!;return {kind:'engineer',principal:{engineer_id:ENGINEER,binding_id:b.binding_id,binding_generation:b.binding_generation,engineer_contract_revision:b.engineer_contract_revision}};}
function demand(root:string,id='22222222-2222-4222-8222-222222222222'){const a=actor(root);if(a.kind!=='engineer')throw new Error();return buildWorkDemand({repository_id:repoHarnessRepoIdFor(root),demand_id:id,idempotency_key:'proposal',source_engineer:a.principal,source_capability_id:CAP,target_capability_id:'capability.workflow-engine.contract-assets',target_engineer_id:null,problem:'Need work.',desired_outcome:'Create task.',contract_escape_reason:'Outside contract.',resource_refs:[],requested_urgency:'normal',dependency_hints:[],created_at:'2026-09-04T00:00:00.000Z'});}
function propose(root:string,d= demand(root),hook?:()=>void){return transitionWorkDemand({repo_root:root,demand:d,idempotency_key:'proposal',transition:'propose',expected_current_digest:null,actor:actor(root),acceptance:null,materialization_receipt:null,crash_hook:hook?boundary=>{if(boundary==='after_event_fsync')hook();}:undefined});}
describe('issue #285 WorkDemand store',()=>{
  test('replays exact proposal, rejects conflicting global key and repairs an event-only crash',()=>{const root=fixture();const first=propose(root);expect(propose(root).event.event_sha256).toBe(first.event.event_sha256);expect(()=>propose(root,demand(root,'33333333-3333-4333-8333-333333333333'))).toThrow(WorkDemandStoreError);const second=fixture();expect(()=>propose(second,demand(second),()=>{throw new Error('crash');})).toThrow('crash');expect(propose(second).current.state).toBe('proposed');expect(readWorkDemandStatus(second,demand(second).demand_id).current.revision).toBe(1);});
  test('a replaced Binding cannot submit as the old requester',()=>{const root=fixture();const d=demand(root);const proposed=propose(root,d);const old=actor(root);const profile=loadEngineerProfile(root,ENGINEER);retireEngineer(root,{engineer_id:ENGINEER,idempotency_key:'retire',expected_current_digest:readEngineerBindingStatus(root,ENGINEER,profile.engineer_contract_revision).current.current_digest,expected_binding_generation:1,expected_binding_id:BINDING,expected_engineer_contract_revision:profile.engineer_contract_revision,now:()=> '2026-09-04T00:01:00.000Z'});expect(()=>transitionWorkDemand({repo_root:root,demand:d,idempotency_key:'submit',transition:'submit',expected_current_digest:proposed.current.current_digest,actor:old,acceptance:null,materialization_receipt:null})).toThrow('does not match exact current Binding');});
});
