import { afterEach, describe, expect, test } from 'bun:test';
import { execFileSync } from 'child_process';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';

import { buildAcceptedWorkDemandProjection, buildWorkDemand } from '../../src/core/engineers/work-demand';
import { projectWorkGraph, validateWorkGraph } from '../../src/core/engineers/scheduling';
import { projectCanonicalTasks } from '../../src/core/state/coordination-identity';
import { materializeWorkDemand, WorkDemandMaterializationError } from '../../src/effects/engineers/work-demand-materialization';
import { readWorkDemandPublicationIntent } from '../../src/effects/engineers/work-demand-store';
import { repoHarnessRepoIdFor } from '../../src/effects/repo-registry';
import { resolveRepoIdentity } from '../../src/effects/state/coordination-canonical-source';

const roots:string[]=[];const TASK='a'.repeat(64);const SPRINT='plans/sprints/demand.sprint.md';const D=`sha256:${'b'.repeat(64)}`;
afterEach(()=>{while(roots.length)rmSync(roots.pop()!,{recursive:true,force:true});});
function fixture(){const root=mkdtempSync(join(tmpdir(),'work-demand-'));roots.push(root);execFileSync('git',['init','-q','--initial-branch=main'],{cwd:root});execFileSync('git',['config','user.email','test@example.invalid'],{cwd:root});execFileSync('git',['config','user.name','Test'],{cwd:root});mkdirSync(join(root,'plans/sprints'),{recursive:true});const sprint=`# Sprint: demand\n\n> **Status**: Approved\n> **Backlog Schema**: 2\n\n## Backlog\n\n| # | ID | Status | Task | Mode | Acceptance | Plan |\n|---|----|---|---|---|---|---|\n\n## Execution Log\n`;writeFileSync(join(root,SPRINT),sprint);const repo=repoHarnessRepoIdFor(root);writeFileSync(join(root,'plans/sprints/demand.work-graph.v1.json'),`${JSON.stringify({protocol:1,kind:'repo-harness-work-graph',repository_id:repo,sprint_path:SPRINT,lane:'generic-v1',work_packages:[]},null,2)}\n`);execFileSync('git',['add','.'],{cwd:root});execFileSync('git',['commit','-qm','base'],{cwd:root});return {root,repo,sprint};}
function accepted(root:string,repo:string,sprint:string){const demand=buildWorkDemand({repository_id:repo,demand_id:'11111111-1111-4111-8111-111111111111',idempotency_key:'proposal',source_engineer:{engineer_id:'engineer:capability.verification.evals-checks',binding_id:'22222222-2222-4222-8222-222222222222',binding_generation:1,engineer_contract_revision:D},source_capability_id:'capability.verification.evals-checks',target_capability_id:'capability.workflow-engine.contract-assets',target_engineer_id:'engineer:capability.workflow-engine.contract-assets',problem:'Need authoritative work.',desired_outcome:'One canonical task.',contract_escape_reason:'Outside current contract.',resource_refs:[],requested_urgency:'normal',dependency_hints:[],created_at:'2026-09-04T00:00:00.000Z'});const graph=validateWorkGraph(JSON.parse(readFileSync(join(root,'plans/sprints/demand.work-graph.v1.json'),'utf8')));const revision=projectWorkGraph(graph,projectCanonicalTasks({repoIdentity:resolveRepoIdentity(root),sprintPath:SPRINT,sprintText:sprint}).map((x,i)=>({task_id:x.task_id,task_revision:x.task_revision,task_ref:x.row.task,status:x.row.status,row_order:i+1}))).work_graph_revision;const projection=buildAcceptedWorkDemandProjection({demand_id:demand.demand_id,demand_sha256:demand.demand_sha256,accepted_from_current_digest:D,sprint_path:SPRINT,expected_sprint_commit:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),expected_work_graph_revision:revision,task_id:TASK,task_text:'Implement accepted demand',task_mode:'contract',acceptance_text:'Exact receipt exists',work_package:{work_package_id:'accepted-demand',task_id:TASK,primary_capability:'capability.workflow-engine.contract-assets',depends_on:[],priority:50,concurrency:{scope:'repo',key:'accepted-demand'},execution_surface:'contract',integration_group:null,required_acceptance:[{gate:'module',policy_id:'accepted-demand',policy_ref:'plans/policies/accepted-demand.json',policy_revision:D}],retry_policy: { max_automated_attempts: 3, retryable_failure_classes: ['transient_failure'], backoff: { kind: 'exponential', initial_seconds: 30, maximum_seconds: 300 }, attention_after_seconds: 3600, revision_reset: 'reset_on_work_package_revision' } as const,
    rollback_boundary:{kind:'work_package',boundary_id:'accepted-demand',boundary_ref:'plans/rollback/accepted-demand.json',boundary_revision:D}},planning_required:true});return {demand,projection};}

describe('issue #285 atomic materialization',()=>{
  test('publishes Sprint and Work Graph in one CAS commit and identical replay returns the receipt',()=>{const {root,repo,sprint}=fixture();const {demand,projection}=accepted(root,repo,sprint);const receipt=materializeWorkDemand({repo_root:root,demand,projection,now:()=> '2026-09-04T01:00:00.000Z'});expect(execFileSync('git',['diff-tree','--no-commit-id','--name-only','-r',receipt.materialized_commit],{cwd:root,encoding:'utf8'}).trim().split('\n').sort()).toEqual([SPRINT,'plans/sprints/demand.work-graph.v1.json'].sort());expect(execFileSync('git',['show',`${receipt.materialized_commit}:${SPRINT}`],{cwd:root,encoding:'utf8'})).toContain(TASK);expect(materializeWorkDemand({repo_root:root,demand,projection})).toEqual(receipt);});
  test('a crash after either blob leaves the canonical ref untouched',()=>{for(const boundary of ['after_sprint_blob','after_graph_blob'] as const){const {root,repo,sprint}=fixture();const {demand,projection}=accepted(root,repo,sprint);expect(()=>materializeWorkDemand({repo_root:root,demand,projection,crash_hook:value=>{if(value===boundary)throw new Error('crash');}})).toThrow('cannot create atomic');expect(execFileSync('git',['rev-parse','main'],{cwd:root,encoding:'utf8'}).trim()).toBe(projection.expected_sprint_commit);}});
  test('recovers the exact receipt after a crash following ref CAS without mutating the ref twice',()=>{const {root,repo,sprint}=fixture();const {demand,projection}=accepted(root,repo,sprint);expect(()=>materializeWorkDemand({repo_root:root,demand,projection,now:()=> '2026-09-04T01:00:00.000Z',crash_hook:value=>{if(value==='after_ref_cas')throw new Error('crash');}})).toThrow('cannot create atomic');const published=execFileSync('git',['rev-parse','main'],{cwd:root,encoding:'utf8'}).trim();const reflogBefore=execFileSync('git',['reflog','show','--format=%H','main'],{cwd:root,encoding:'utf8'});const receipt=materializeWorkDemand({repo_root:root,demand,projection});expect(receipt.materialized_commit).toBe(published);expect(execFileSync('git',['reflog','show','--format=%H','main'],{cwd:root,encoding:'utf8'})).toBe(reflogBefore);});
  test('finishes a journaled pre-CAS publication using the original receipt and commit',()=>{const {root,repo,sprint}=fixture();const {demand,projection}=accepted(root,repo,sprint);expect(()=>materializeWorkDemand({repo_root:root,demand,projection,now:()=> '2026-09-04T01:00:00.000Z',crash_hook:value=>{if(value==='before_ref_cas')throw new Error('crash');}})).toThrow('cannot create atomic');const intent=readWorkDemandPublicationIntent(root,demand.demand_id)!;expect(execFileSync('git',['rev-parse','main'],{cwd:root,encoding:'utf8'}).trim()).toBe(projection.expected_sprint_commit);const receipt=materializeWorkDemand({repo_root:root,demand,projection});expect(receipt).toEqual(intent.receipt);expect(execFileSync('git',['rev-parse','main'],{cwd:root,encoding:'utf8'}).trim()).toBe(intent.materialized_commit);});
  test('rejects recovery when the canonical target moved somewhere other than the journaled commit',()=>{const {root,repo,sprint}=fixture();const {demand,projection}=accepted(root,repo,sprint);expect(()=>materializeWorkDemand({repo_root:root,demand,projection,now:()=> '2026-09-04T01:00:00.000Z',crash_hook:value=>{if(value==='before_ref_cas')throw new Error('crash');}})).toThrow('cannot create atomic');const tree=execFileSync('git',['rev-parse','HEAD^{tree}'],{cwd:root,encoding:'utf8'}).trim();const unrelated=execFileSync('git',['commit-tree',tree,'-p','HEAD','-m','unrelated'],{cwd:root,encoding:'utf8'}).trim();execFileSync('git',['update-ref','refs/heads/main',unrelated,projection.expected_sprint_commit],{cwd:root});expect(()=>materializeWorkDemand({repo_root:root,demand,projection})).toThrow('canonical target moved after publication intent');});
});
