import { describe, expect, test } from 'bun:test';
import { mkdtempSync, rmSync } from 'fs'; import { tmpdir } from 'os'; import { join } from 'path'; import { spawnSync } from 'child_process';
import { buildLeaseOwnerRecord } from '../../src/core/state/coordination-identity';
import { buildLeaseLivenessPolicy } from '../../src/core/state/lease-liveness';
import { createLeaseDirectory, readLease, writeLeaseOwnerDurably } from '../../src/effects/state/coordination-lease-store';
import { renewLeaseLiveness } from '../../src/effects/state/coordination-lease-liveness-store';
import { automaticReclaimLease, observeLeaseReclaimEligibility } from '../../src/effects/state/coordination-lease-reclaim';
const task = 'a'.repeat(64); const revision = 'b'.repeat(64); const SHA = `sha256:${'c'.repeat(64)}`;
const evidence = { controller_terminal: true, runtime_effect_inactive: true, publication_inactive: true, binding_generation_matches: true, claim_actor_matches: true, evidence_revision: SHA } as const;
const policy = buildLeaseLivenessPolicy({ renewal_interval_ms: 1_000, maximum_ttl_ms: 10_000, renewal_actor_kind: 'controller', required_evidence_sources: ['controller', 'runtime_effect', 'publication', 'binding'], unproven_behavior: 'require_attention' });
function setup() { const root = mkdtempSync(join(tmpdir(), 'lease-reclaim-')); spawnSync('git', ['init', '-q'], { cwd: root }); const owner = buildLeaseOwnerRecord({ claimId: 'claim-1', taskId: task, taskRevision: revision, sprintPath: 'plans/sprints/a.md', targetRef: 'main', generation: 1, sessionId: 'old', sourceWorktree: '/old' }); createLeaseDirectory(root, task); writeLeaseOwnerDurably(root, task, owner); renewLeaseLiveness({ repo_root: root, owner, policy, owner_id: 'controller-1', observed_at: '2026-09-04T00:00:00.000Z', requested_ttl_ms: 1_000, binding_generation: 1, runtime_effect_id: null, expected_current_sha256: null }); return root; }
describe('issue #286 automatic Lease reclaim', () => {
  test('revalidates exact evidence under lock and increments one generation', () => { const root = setup(); try { const now = () => new Date('2026-09-04T00:00:02.000Z'); const receipt = observeLeaseReclaimEligibility({ repo_root: root, task_id: task, evidence, publication_state: 'inactive', now }); const next = automaticReclaimLease({ repo_root: root, receipt, session_id: 'new', source_worktree: '/new', reason: 'owner-terminal', observe_evidence: () => ({ evidence, publication_state: 'inactive' }), now, new_claim_id: () => 'claim-2' }); expect(next.generation).toBe(2); expect(readLease(root, task).record?.claim_id).toBe('claim-2'); expect(() => automaticReclaimLease({ repo_root: root, receipt, session_id: 'other', source_worktree: '/other', reason: 'race', observe_evidence: () => ({ evidence, publication_state: 'inactive' }), now })).toThrow(); } finally { rmSync(root, { recursive: true, force: true }); } });
  test('refuses changed evidence and publication recovery', () => { const root = setup(); try { const now = () => new Date('2026-09-04T00:00:02.000Z'); const receipt = observeLeaseReclaimEligibility({ repo_root: root, task_id: task, evidence, publication_state: 'inactive', now }); expect(() => automaticReclaimLease({ repo_root: root, receipt, session_id: 'new', source_worktree: '/new', reason: 'changed', observe_evidence: () => ({ evidence: { ...evidence, evidence_revision: `sha256:${'d'.repeat(64)}` }, publication_state: 'inactive' }), now })).toThrow('stale'); expect(observeLeaseReclaimEligibility({ repo_root: root, task_id: task, evidence, publication_state: 'reviewing', now }).classification).toBe('publication_recovery_required'); } finally { rmSync(root, { recursive: true, force: true }); } });
});
