import { describe, expect, test } from 'bun:test';
import { assertReclaimReceiptCurrent, buildLeaseLivenessPolicy, buildLeaseRenewalObservation, classifyLeaseReclaim, foldLeaseLivenessCurrent } from '../../src/core/state/lease-liveness';

const SHA = `sha256:${'a'.repeat(64)}`;
const policy = buildLeaseLivenessPolicy({ renewal_interval_ms: 1_000, maximum_ttl_ms: 10_000, renewal_actor_kind: 'controller', required_evidence_sources: ['controller', 'runtime_effect', 'publication', 'binding'], unproven_behavior: 'require_attention' });
function renewal(previous = null as ReturnType<typeof buildLeaseRenewalObservation> | null) { return buildLeaseRenewalObservation({ policy, task_id: 't'.repeat(64), task_revision: 'r'.repeat(64), claim_id: 'claim-1', lease_generation: 1, owner_id: 'controller-1', execution_worktree: '/work', branch: 'codex/work', observed_at: previous ? '2026-09-04T00:00:02.000Z' : '2026-09-04T00:00:00.000Z', requested_ttl_ms: 2_000, binding_generation: 1, runtime_effect_id: null, previous }); }
const dead = { controller_terminal: true, runtime_effect_inactive: true, publication_inactive: true, binding_generation_matches: true, claim_actor_matches: true, evidence_revision: SHA } as const;

describe('issue #286 lease liveness contract', () => {
  test('builds a bounded policy and one monotonic digest chain', () => { const first = renewal(); const second = renewal(first); expect(second.sequence).toBe(2); expect(second.previous_renewal_sha256).toBe(first.renewal_sha256); expect(foldLeaseLivenessCurrent(second).last_renewal_sha256).toBe(second.renewal_sha256); expect(() => buildLeaseLivenessPolicy({ ...policy, maximum_ttl_ms: 999 } as never)).toThrow(); });
  test('expiry alone never permits reclaim', () => { const current = renewal(); const unknown = classifyLeaseReclaim({ renewal: current, task_revision: current.task_revision, classified_at: '2026-09-04T00:00:03.000Z', evidence: { ...dead, controller_terminal: null }, publication_state: 'inactive' }); expect(unknown.classification).toBe('liveness_unproven'); const active = classifyLeaseReclaim({ renewal: current, task_revision: current.task_revision, classified_at: '2026-09-04T00:00:03.000Z', evidence: { ...dead, runtime_effect_inactive: false }, publication_state: 'inactive' }); expect(active.classification).toBe('expired_but_effect_active'); });
  test('protects publication and emits an exact reclaim fence', () => { const current = renewal(); expect(classifyLeaseReclaim({ renewal: current, task_revision: current.task_revision, classified_at: '2026-09-04T00:00:03.000Z', evidence: dead, publication_state: 'reviewing' }).classification).toBe('publication_recovery_required'); const receipt = classifyLeaseReclaim({ renewal: current, task_revision: current.task_revision, classified_at: '2026-09-04T00:00:03.000Z', evidence: dead, publication_state: 'inactive' }); expect(receipt.classification).toBe('reclaimable'); expect(() => assertReclaimReceiptCurrent(receipt, { task_revision: current.task_revision, claim_id: current.claim_id, lease_generation: 2, renewal_sha256: current.renewal_sha256, evidence_revision: SHA })).toThrow('stale'); });
});
