import { afterAll, describe, expect, test } from 'bun:test';
import { createHash } from 'crypto';
import { execFileSync } from 'child_process';
import { mkdtempSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { promoteRefactorActivation, REFACTOR_CANARIES_BY_LEVEL, REFACTOR_CANARY_IDS, buildRefactorCanaryReceipt, type RefactorCanaryId } from '../../src/core/refactor/activation';
import { advanceRefactorActivation, appendRefactorCanaryReceipt, readRefactorActivationLevel } from '../../src/effects/refactor/activation-store';
const roots: string[] = []; const digest = (value: string) => `sha256:${createHash('sha256').update(value).digest('hex')}`; const observedAt = '2026-09-04T08:00:00.000Z';
function receipt(id: RefactorCanaryId, targetRevision = 'a'.repeat(40), passed = true) { return buildRefactorCanaryReceipt({ canaryId: id, repositoryId: 'repo.activation', targetRevision, passed, evidenceRefs: [{ locator: `tests/canaries/${id}`, sha256: digest(id) }], observedAt }); }
afterAll(() => roots.forEach((root) => rmSync(root, { recursive: true, force: true })));
describe('Module 10 evidence-gated activation ladder', () => {
  test('freezes ten canaries and rejects skips, failures, and foreign evidence', () => { expect(REFACTOR_CANARY_IDS).toHaveLength(10); expect(() => promoteRefactorActivation({ currentLevel: 'off', nextLevel: 'active_module', repositoryId: 'repo.activation', targetRevision: 'a'.repeat(40), receipts: REFACTOR_CANARY_IDS.map((id) => receipt(id)), observedAt })).toThrow('exactly one level'); expect(() => promoteRefactorActivation({ currentLevel: 'off', nextLevel: 'shadow', repositoryId: 'repo.activation', targetRevision: 'a'.repeat(40), receipts: [receipt('version_mismatch_fail_closed', 'a'.repeat(40), false)], observedAt })).toThrow('did not pass'); expect(() => promoteRefactorActivation({ currentLevel: 'off', nextLevel: 'shadow', repositoryId: 'repo.activation', targetRevision: 'a'.repeat(40), receipts: [receipt('version_mismatch_fail_closed', 'b'.repeat(40))], observedAt })).toThrow('not bound'); });
  test('advances off to cross-module one rung at a time from repository-local receipts', () => { const root = mkdtempSync(join(tmpdir(), 'refactor-activation-')); roots.push(root); execFileSync('git', ['init', '-q'], { cwd: root }); execFileSync('git', ['config', 'user.email', 'fixture@example.com'], { cwd: root }); execFileSync('git', ['config', 'user.name', 'Fixture'], { cwd: root }); execFileSync('git', ['commit', '--allow-empty', '-qm', 'baseline'], { cwd: root }); const head = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim(); for (const id of REFACTOR_CANARY_IDS) appendRefactorCanaryReceipt(root, { canaryId: id, repositoryId: 'repo.activation', targetRevision: head, passed: true, evidenceRefs: [{ locator: `tests/canaries/${id}`, sha256: digest(id) }], observedAt }); expect(readRefactorActivationLevel(root)).toBe('off'); for (const next_level of ['shadow', 'active_module', 'active_cross_module'] as const) { const event = advanceRefactorActivation({ repo_root: root, repository_id: 'repo.activation', target_revision: head, next_level, observed_at: observedAt }); expect(event.canaryReceiptSha256).toHaveLength(REFACTOR_CANARIES_BY_LEVEL[next_level].length); expect(readRefactorActivationLevel(root)).toBe(next_level); } });
});
